### ISSUE TITLE
Ellips angular spread unit is radian**2 ELN accepts, but parser claims it being incompatible unit for ANGLE

### ISSUE THREAD

**Issue by sanbrock** [FAIRmat-Experimental/data-modeling#58]
I think there was also some gui issue for the value being present in pint but not in the unit registry we use in the gui system (We may have used steradian in the past and I may have changed it to radian\*\*2). I don't really know the issue in detail but from just the text being written I would also say that reject radian\*\*2 as an ANGLE is correct, radian is a unit of angle and radian\*\*2 is a unit of solid angle / steradian.

**Comment by domna** [comment]
I get a second error while parsing this file:
```
The shape of nexus.NXellipsometry.NXentry.NXsample.column_names__field:Quantity requires an iterable value, but ['psi' 'delta'] is not iterable. 
```

**Comment by domna** [comment]
I changed to unit to `radian` in the eln in north/dev and updated it in the sprint branch. If we have any objections that this value has unit radian we have to revert it.
