### ISSUE TITLE
dispersion base class for ellipsometry

### ISSUE THREAD

**Issue by sanbrock** [FAIRmat-Experimental/data-modeling#61]

**Comment by tomio13** [comment]
An interesting question. In our VASE system this is basically:
 - an array of wavelength, n and k values (complex refractive index: n + ik)
 - a definition whether this curve is a result of:
   -  a model --> then which model was used:
     - Cauchy
     - Lorentz oscillator
     - ...
   - directly measured
     - reference to measurement
So, such things could be addressed in this definition.

**Comment by domna** [comment]
Yes, I actually split the dispersion of into two parts: tabulated (n,k or epsilon vs. wavelength/energy) and function (for Cauchy, Lorentz and others). My plan is to construct this dispersions only as extracted values, hence they are either tabulated or a function and can be attached to the measurement as a NXprocess. The idea is to store the model from a measurement in this NXprocess (I could also think of a PseudoDielectric Dispersion if it is calculated directly from an absorptive substrate - but I think even in this case it is better to construct an optical model and tmm calculation).

I also allow adding multiple models together (e.g. a model could be a combination of Cauchy + Lorentz let's say, which makes not sense for all combinations) and the basic building block I called `DispersiveMaterial`, which can hold up to three dispersions (from which two are optional) account for biaxial materials. I'm just writing up the basic structure as an nxdl yaml and probably will push it today so I'd be happy if you'd take a look then (I will link the PR here).

**Comment by domna** [comment]
@tomio13 You can find the draft here: #68
